### PR TITLE
Added monochrome image colorization papers. Fixes #44

### LINKED ISSUE #44: Colorization papers
There is some recent work on colorizing monochrome images:
[Colorful Image Colorization](http://arxiv.org/pdf/1603.08511.pdf) Richard Zhang, Phillip Isola, Alexei A. Efros, ECCV 2016
https://github.com/richzhang/colorization

Ryan Dahl 
http://tinyclouds.org/colorize/

I'm not sure where should this go, or if there should be a separate section for it - I can submit a PR once you let me know

### PR DESCRIPTION
**Pull request by mihaibujanca**

### CODE REVIEW

**Comment by kjw0612** [comment]
Blog post adds a line. Is that on purpose? I think you can just add the post like [Blog] at the end of the paper.

**Comment by mihaibujanca** [comment]
@kjw0612 No, my mistake. Updated.
There's no paper associated with what Ryan Dalh does, as far as I know, but the other paper does compare their results to his, and looks like his work is ongoing.

**Comment by kjw0612** [comment]
This has some conflicts.

**Comment by mihaibujanca** [comment]
Sorry for taking so long. This one is fixed

**Pull request merged**
